### ISSUE TITLE
Cannot perform most actions on an Issue

### ISSUE THREAD

**Issue by j-applese3d** [AntonShuvaev/intellij-sentry#1]
**Describe the bug**
Resolve Issue, and other action buttons are greyed out

**Steps to reproduce**
Not sure, but I had entered in an Auth-Token with the default permissions (that Sentry pre-selects) at first.
Since then I removed & created a new token granting only the permissions specified https://plugins.jetbrains.com/plugin/22232-sentry

**Expected behavior**
Resolve Issue and other buttons should work.
![image](https://github.com/AntonShuvaev/intellij-sentry/assets/24463871/38f59765-7615-4866-a9fb-101d84283adf)

**Environment information:**
- OS: Ubuntu 22.04
PhpStorm 2023.2
Build #PS-232.8660.205, built on July 28, 2023
    com.intellij-sentry (1.0.4-232)

**Comment by AntonShuvaev** [comment]
Hello,

To enable the action buttons, select one or more issues by ticking the checkboxes on the left side of each issue. Once selected, the actions should become available.
